---
abstract: 'modules implementing common methods for applications'
author:
  - 'Binary.com <binary@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Slurp: '0'
  Test::Exit: '0'
  Test::FailWarnings: '0'
  Test::More: '0.94'
  Test::Most: '0.21'
  Text::Trim: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Base
no_index:
  directory:
    - t
    - inc
requires:
  File::Flock::Tiny: '0'
  List::Util: '0'
  Log::Log4perl: '0'
  Moose: '0'
  Moose::Role: '0'
  MooseX::Types: '0'
  Path::Tiny: '0'
  Text::Reform: '0'
  Try::Tiny: '0'
  namespace::autoclean: '0'
  perl: '5.01'
resources:
  bugtracker: https://github.com/binary-com/perl-App-Base/issues
  homepage: https://github.com/binary-com/perl-App-Base
  license: http://dev.perl.org/licenses/
  repository: git://github.com/binary-com/perl-App-Base
version: '0.04'
x_contributors:
  - 'Calum Halcrow'
  - 'Chris Travers'
  - 'Fayland Lam <fayland@gmail.com>'
  - 'Jean-Yves Sireau'
  - 'Kaveh Mousavi Zamani'
  - 'Matt Miller'
  - 'Nick Marden'
  - 'Pavel Shaydo <zwon@cpan.org>'
  - 'Tee Shuwn Yuan'
